# Generated by Django 4.0.6 on 2022-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=100)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('log_error', models.CharField(max_length=100)),
            ],
        ),
    ]
