# Generated by Django 4.0.6 on 2022-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtable',
            name='log_error',
        ),
        migrations.AddField(
            model_name='logtable',
            name='log_error_Message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='log_type',
            field=models.CharField(choices=[('info', 'info'), ('error', 'error'), ('debug', 'debug'), ('track', 'track'), ('critical', 'critical'), ('warning', 'warning')], max_length=100),
        ),
    ]
