# Generated by Django 4.0.6 on 2022-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_logtable_log_error_logtable_log_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='log_type',
            field=models.CharField(choices=[('0', 'not_set'), ('20', 'info'), ('40', 'error'), ('10', 'debug'), ('50', 'critical'), ('30', 'warning')], max_length=100),
        ),
    ]
